supermarket/iSupermarket/urls.py
from django.conf.urls import patterns, include, url
from models import *
#from filmApplication.forms import ActorForm, DirectorForm, MovieForm, ReviewForm
from views import *
from django.contrib import admin
from viewsEloi import *
#from forms import ClientForm

from django.conf.urls import patterns, url, include
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView
from rest_framework.urlpatterns import format_suffix_patterns


admin.autodiscover()

urlpatterns = patterns('',
    #Url de inici
    url(r'^$', Inici.as_view(),),
    url(r'^Client/$',Clients.as_view(),name="client_list"),
    url(r'^Marca/$',Marcas.as_view(),name="marca_list"),
    url(r'^Producte/$',Productes.as_view(),name="producte_list"),
    url(r'^Companyia/$',Companyias.as_view(),name="companyia_list"),
    url(r'^Sucursal/$',Sucursals.as_view(),name="sucursal_list"),
    url(r'^Client/(?P<pk>\d+)/$',ClientDetail.as_view(),name='client_detail'),
    url(r'^Client/(?P<pk>\d+)/edit/$',ClientUpdate.as_view(), name='client_update'),
    url(r'^Client/(?P<pk>\d+)/delete/$',ClientDelete.as_view(), name='client_delete'),
    url(r'^Companyia/(?P<pk>\d+)/$',CompanyiaDetail.as_view(),name='companyia_detail'),
    url(r'^Companyia/(?P<pk>\d+)/edit/$',CompanyiaUpdate.as_view(), name='companyia_update'),
    url(r'^Companyia/(?P<pk>\d+)/delete/$',CompanyiaDelete.as_view(), name='companyia_delete'),
    url(r'^Sucursal/(?P<pk>\d+)/$',SucursalDetail.as_view(),name='sucursal_detail'),
    url(r'^Sucursal/(?P<pk>\d+)/edit/$','iSupermarket.views.SucursalUpdate2', name='sucursal_update'),
    url(r'^Sucursal/(?P<pk>\d+)/delete/$',SucursalDelete.as_view(), name='sucursal_delete'),
    url(r'^Marca/(?P<pk>\d+)/$',MarcaDetail.as_view(), name='marca_detail'),
    url(r'^Marca/(?P<pk>\d+)/edit/$',MarcaUpdate.as_view(), name='marca_update'),
    url(r'^Marca/(?P<pk>\d+)/delete/$',MarcaDelete.as_view(), name='marca_delete'),
    url(r'^Producte/(?P<pk>\d+)/$',ProducteDetail.as_view(), name = 'producte_detail'),
    url(r'^Producte/(?P<pk>\d+)/edit/$','iSupermarket.views.ProducteUpdate2', name='producte_update'),
    url(r'^Producte/(?P<pk>\d+)/delete/$',ProducteDelete.as_view(), name='producte_delete'),
    url(r'^Client/create/$',ClientCreate.as_view(),name='client_create'),
    url(r'^Producte/create/$','iSupermarket.views.ProducteCreate2',name='producte_create'),
    url(r'^Marca/create/$',MarcaCreate.as_view(),name='marca_create'),
    url(r'^Sucursal/create/$','iSupermarket.views.SucursalCreate2',name='sucursal_create'),
    url(r'^Companyia/create/$',CompanyiaCreate.as_view(),name='companyia_create'),
    url(r'^Client\.(?P<extension>(json|xml))$', Clients.as_view(), name='client_list_conneg'),
    url(r'^Marca\.(?P<extension>(json|xml))$', Marcas.as_view(), name='marca_list_conneg'),
    url(r'^Producte\.(?P<extension>(json|xml))$', Productes.as_view(), name='producte_list_conneg'),
    url(r'^Sucursal\.(?P<extension>(json|xml))$', Sucursals.as_view(), name='sucursal_list_conneg'),
    url(r'^Companyia\.(?P<extension>(json|xml))$', Companyias.as_view(), name='companyia_list_conneg'),
    url(r'^Client/(?P<pk>\d+)\.(?P<extension>(json|xml))$', ClientDetail.as_view(), name='client_detail_conneg'),
    url(r'^Marca/(?P<pk>\d+)\.(?P<extension>(json|xml))$', MarcaDetail.as_view(), name='marca_detail_conneg'),
    url(r'^Producte/(?P<pk>\d+)\.(?P<extension>(json|xml))$', ProducteDetail.as_view(), name='producte_detail_conneg'),
    url(r'^Sucursal/(?P<pk>\d+)\.(?P<extension>(json|xml))$', SucursalDetail.as_view(), name='sucursal_detail_conneg'),
    url(r'^Companyia/(?P<pk>\d+)\.(?P<extension>(json|xml))$', CompanyiaDetail.as_view(), name='companyia_detail_conneg'),
    url(r'^Register/$',UserCreate.as_view(),name='user_create'),
    url(r'^Sucursal/(?P<pk>\d+)/reviews/create/$', 'iSupermarket.views.review', name='review_create'),
)

#RESTful API
urlpatterns += patterns('',
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/Clients/$', APIClientList.as_view(), name='client-list'),
    url(r'^api/Clients/(?P<pk>\d+)/$', APIClientDetail.as_view(), name='client-detail'),
    url(r'^api/Sucursals/$', APISucursalList.as_view(), name='sucursal-list'),
    url(r'^api/Sucursals/(?P<pk>\d+)/$', APISucursalDetail.as_view(), name='sucursal-detail'),
    url(r'^api/Marca/$', APIMarcaList.as_view(), name='marca-list'),
    url(r'^api/Marca/(?P<pk>\d+)/$', APIMarcaDetail.as_view(), name='marca-detail'),
    url(r'^api/Producte/$', APIProducteList.as_view(), name='producte-list'),
    url(r'^api/Producte/(?P<pk>\d+)/$', APIProducteDetail.as_view(), name='producte-detail'),
    url(r'^api/Companyia/$', APICompanyiaList.as_view(), name='companyia-list'),
    url(r'^api/Companyia/(?P<pk>\d+)/$', APICompanyiaDetail.as_view(), name='companyia-detail'),
    url(r'^api/sucursalreviews/$', APISucursalReviewList.as_view(), name='sucursalreview-list'),
    url(r'^api/sucursalreviews/(?P<pk>\d+)/$', APISucursalReviewDetail.as_view(), name='sucursalreview-detail'),
    
)

# Format suffixes
urlpatterns = format_suffix_patterns(urlpatterns, allowed=['api','json', 'xml'])

supermarket/supermarket/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin


admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'supermarket.views.home', name='home'),
    #url(r'^blog/', include('blog.urls')),
	url(r'^app/', include('iSupermarket.urls', namespace='iSupermarket')),
	url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout'),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
)

supermarket/iSupermarket/forms.py
from django.forms import ModelForm, ModelChoiceField
from models import Client, Companyia, Marca, Producte, Sucursal
from django.contrib.auth.models import User

class ClientForm(ModelForm):
    class Meta:
        model = Client
        exclude = ('registration_date','user')

class CompanyiaForm(ModelForm):
    class Meta:
        model = Companyia
        exclude = ('user',)

class MarcaForm(ModelForm):
    class Meta:
        model = Marca
        exclude =('user',)

class ProducteForm(ModelForm):
    class Meta:
        model = Producte
        exclude =('user',)

class ProducteForm2(ModelForm):
    user = User
    class Meta:
        model = Producte
        exclude =('user',)

    def __init__(self, user, *args, **kwargs):
        super(ProducteForm2, self).__init__(*args,**kwargs)
        self.user = user
        self.fields['marca'] = ModelChoiceField(Marca.objects.filter(user=user),to_field_name="id")

    def save(self):
        producte = super(ProducteForm2, self).save(commit=False)
        producte.user = self.user
        producte.save()
        return producte

class SucursalForm(ModelForm):
    class Meta:
        model = Sucursal
        exclude =('user',)


class SucursalForm2(ModelForm):
    user = User
    class Meta:
        model = Sucursal
        exclude =('user',)

    def __init__(self, user, *args, **kwargs):
        super(SucursalForm2, self).__init__(*args,**kwargs)
        self.user = user
        print user
        self.fields['companyia'] = ModelChoiceField(Companyia.objects.filter(user=user),to_field_name="id")

    def save(self):
        sucursal = super(SucursalForm2, self).save(commit=False)
        sucursal.user = self.user
        sucursal.save()
        return sucursal

supermarket/iSupermarket/views.py
# Create your views here.
from django.core.urlresolvers import reverse, reverse_lazy
from django.core import urlresolvers
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView, ListView, DeleteView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.base import TemplateResponseMixin
from django.core import serializers
from rest_framework import routers, serializers, viewsets

from models import Client, Companyia, Marca, Producte, Sucursal
from forms import *
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from rest_framework import generics, permissions
from serializers import *


from django.shortcuts import render, render_to_response, RequestContext


class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)

@login_required()
def review(request, pk):
    sucursal = get_object_or_404(Sucursal, pk=pk)
    new_review = SucursalReview(
        rating=request.POST['rating'],
        comment=request.POST['comment'],
        user=request.user,
        sucursal=sucursal)
    new_review.save()
    return HttpResponseRedirect(urlresolvers.reverse('iSupermarket:sucursal_detail', args=(sucursal.id,)))

class CheckIsOwnerMixin(object):
    def get_object(self, *args, **kwargs):
        obj = super(CheckIsOwnerMixin, self).get_object(*args, **kwargs)
        if not obj.user == self.request.user:
            raise PermissionDenied
        return obj


class ConnegResponseMixin(TemplateResponseMixin):

    def render_json_object_response(self, objects, **kwargs):
        json_data = serializers.serialize(u"json", objects, **kwargs)
        return HttpResponse(json_data, content_type=u"application/json")

    def render_xml_object_response(self, objects, **kwargs):
        xml_data = serializers.serialize(u"xml", objects, **kwargs)
        return HttpResponse(xml_data, content_type=u"application/xml")

    def render_to_response(self, context, **kwargs):
        if 'extension' in self.kwargs:
            try:
                objects = [self.object]
            except AttributeError:
                objects = self.object_list
            if self.kwargs['extension'] == 'json':
                return self.render_json_object_response(objects=objects)
            elif self.kwargs['extension'] == 'xml':
                return self.render_xml_object_response(objects=objects)
        else:
            return super(ConnegResponseMixin, self).render_to_response(context)

class Inici(ListView):
    model = Client #Aixo ha de quedar aixi ara que ja no llistem sol clients.
    template_name = 'index.html'
    queryset = Client.objects.all() #Comentari = al anterior.

class Clients(LoginRequiredMixin,ListView,ConnegResponseMixin):
    model = Client
    template_name = 'clients.html'
    queryset = Client.objects.all()
    context_object_name='clients_list'

class Companyias(ListView,ConnegResponseMixin):
    model = Companyia
    template_name = 'companyia.html'
    queryset = Companyia.objects.all()
    context_object_name='Companyia_list'

class Sucursals(ListView,ConnegResponseMixin):
    model = Sucursal
    template_name = 'sucursal.html'
    queryset = Sucursal.objects.all()
    context_object_name='Sucursal_list'

class Marcas(ListView,ConnegResponseMixin):
    model = Marca
    template_name = 'marca.html'
    queryset = Marca.objects.all()
    context_object_name='Marca_list'

class Productes(ListView,ConnegResponseMixin):
    model = Producte
    template_name = 'producte.html'
    queryset = Producte.objects.all()
    context_object_name='Producte_list'

class ClientDetail(DetailView,ConnegResponseMixin):
    model = Client
    template_name = 'detail_client.html'

    def get_context_data(self, **kwargs):
       context = super(ClientDetail, self).get_context_data(**kwargs)
       return context

class CompanyiaDetail(DetailView,ConnegResponseMixin):
    model = Companyia
    template_name = 'detail_companyia.html'

    def get_context_data(self, **kwargs):
       context = super(CompanyiaDetail, self).get_context_data(**kwargs)
       return context


class SucursalDetail(DetailView,ConnegResponseMixin):
    model = Sucursal
    template_name = 'detail_sucursal.html'

    def get_context_data(self, **kwargs):
       context = super(SucursalDetail, self).get_context_data(**kwargs)
       return context

class MarcaDetail(DetailView,ConnegResponseMixin):
    model = Marca
    template_name = 'detail_marca.html'

    def get_context_data(self, **kwargs):
        context = super(MarcaDetail, self).get_context_data(**kwargs)
        return context


class ProducteDetail(DetailView,ConnegResponseMixin):
    model = Producte
    template_name = 'detail_producte.html'

    def get_context_data(self, **kwargs):
        context = super(ProducteDetail, self).get_context_data(**kwargs)
        return context

class ClientCreate(CreateView):
    model = Client
    template_name = 'form_client.html'
    form_class = ClientForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ClientCreate, self).form_valid(form)

class CompanyiaCreate(CreateView):
    model = Companyia
    template_name = 'form_companyia.html'
    form_class = CompanyiaForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CompanyiaCreate, self).form_valid(form)

class MarcaCreate(CreateView):
    model = Marca
    template_name = 'form_marca.html'
    form_class = MarcaForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(MarcaCreate, self).form_valid(form)

class ProducteCreate(CreateView):
    model = Producte
    template_name = 'form_producte.html'
    form_class = ProducteForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(ProducteCreate, self).form_valid(form)

def ProducteCreate2(request):
    if request.method == 'POST':
        formulario = ProducteForm2(request.user, request.POST)
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect('/app/Producte')
    else:
        formulario = ProducteForm2(request.user)
    return render_to_response('form_producte.html',{'form':formulario},context_instance=RequestContext(request))

class SucursalCreate(CreateView):
    model = Sucursal
    template_name = 'form_sucursal.html'
    form_class = SucursalForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(SucursalCreate, self).form_valid(form)

def SucursalCreate2(request):
    if request.method == 'POST':
        formulario = SucursalForm2(request.user, request.POST)
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect('/app/Sucursal')
    else:
        formulario = SucursalForm2(request.user)
    return render_to_response('form_sucursal.html',{'form':formulario},context_instance=RequestContext(request))

class UserCreate(CreateView):
    model = User
    template_name = 'form_user.html'
    form_class = UserCreationForm
    success_url = "/app"

    def form_valid(self,form):
        return super(UserCreate,self).form_valid(form)

class ClientUpdate(UpdateView):
    model=Client
    template_name = 'update_client.html'
    form_class = ClientForm

class ClientDelete(DeleteView):
    model = Client
    success_url = "/app/Client"
    template_name = 'delete_client.html'

class CompanyiaUpdate(UpdateView):
    model=Companyia
    template_name = 'update_companyia.html'
    form_class = CompanyiaForm

class CompanyiaDelete(DeleteView):
    model = Companyia
    success_url = "/app/Companyia"
    template_name = 'delete_companyia.html'

class SucursalUpdate(UpdateView):
    model=Sucursal
    template_name = 'update_sucursal.html'
    form_class = SucursalForm

def SucursalUpdate2(request,pk):
    sucursal = Sucursal.objects.get(id=pk)
    if request.method == 'POST':
        formulario = SucursalForm2(sucursal.user, request.POST, instance=sucursal)
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect('/app/Sucursal')
    else:
        formulario = SucursalForm2(sucursal.user, instance=sucursal)
    return render_to_response('update_sucursal.html',{'form':formulario},context_instance=RequestContext(request))


class SucursalDelete(DeleteView):
    model = Sucursal
    success_url = "/app/Sucursal"
    template_name = 'delete_sucursal.html'


class MarcaUpdate(UpdateView):
    model=Marca
    template_name = 'update_marca.html'
    form_class = MarcaForm

class MarcaDelete(DeleteView):
    model = Marca
    success_url = "/app/Marca"
    template_name = 'delete_marca.html'

class ProducteUpdate(UpdateView):
    model=Producte
    template_name = 'update_producte.html'
    form_class = ProducteForm


def ProducteUpdate2(request,pk):
    producte = Producte.objects.get(id=pk)
    if request.method == 'POST':
        formulario = ProducteForm2(producte.user, request.POST, instance=producte)
        if formulario.is_valid():
            formulario.save()
            return HttpResponseRedirect('/app/Producte')
    else:
        formulario = ProducteForm2(producte.user, instance=producte)
    return render_to_response('update_producte.html',{'form':formulario},context_instance=RequestContext(request))

class ProducteDelete(DeleteView):
    model = Producte
    success_url = "/app/Producte"
    template_name = 'delete_producte.html'

class APIClientList(generics.ListCreateAPIView):
    model = Client

supermarket/iSupermarket/templates/clients.html
{% extends "base.html" %}

{% block content %}
	<h1>
		Clients:
		{% if user.username %}
		<h4><a href="{% url 'iSupermarket:client_create' %}">Afegir nou Client</a></h4>
		{% endif %}
	</h1>
	<ul>
		{% for client in clients_list  %}
				<li><a href="{% url	'iSupermarket:client_detail' client.id %}">{{ client }}</a></li>
		{% empty %}<li> Disculpeu, encara no hi ha cap client/li>
		{% endfor %}
	</ul>
{% endblock %}

supermarket/iSupermarket/templates/companyia.html
{% extends "base.html" %}

{% block content %}
<h1>
	Companyia:
	{% if user.username %}
	<h4><a href="{% url 'iSupermarket:companyia_create' %}">Afegir nova Companyia</a></h4>
	{% endif %}
</h1>
<ul>
	{% for companyia in Companyia_list  %}
		<li><a href="{% url	'iSupermarket:companyia_detail' companyia.id %}">{{ companyia.name }}</li>
	{% empty %}<li> Disculpeu, encara no hi ha cap companyia</li>
	{% endfor %}
</ul>
{% endblock %}

supermarket/iSupermarket/templates/delete_companyia.html
{% extends "base.html" %}
{% block	content	%}
<h1>
	Eliminar Client
</h1>

<form action="" method="post">{% csrf_token %}
    <p>Estas segur que vols eliminar la companyia: "{{ companyia }}"?</p>
    <input type="submit" value="Confirmar" />
</form>

{% endblock %}

supermarket/iSupermarket/templates/delete_sucursal.html
{% extends "base.html" %}
{% block	content	%}
<h1>
	Eliminar Sucursal
</h1>

<form action="" method="post">{% csrf_token %}
    <p>Estas segur que vols eliminar la sucursal: "{{ sucursal }}"?</p>
    <input type="submit" value="Confirmar" />
</form>

{% endblock %}

supermarket/iSupermarket/templates/detail_client.html
{% extends "base.html" %}{% block title %} iSupermarket - {{client}}{% endblock %}{% block	content	%}<span vocab="http://schema.org/" typeof="person"><h1>  <span property = "name">{{ client.name }}</span>  {% if user.is_staff %}    (<a href="{% url 'iSupermarket:client_update' client.id %}">edit</a>) or    (<a href="{% url 'iSupermarket:client_delete' client.id %}">delete</a>)  {% elif user == client.user %}    (<a href="{% url 'iSupermarket:client_update' client.id %}">edit</a>) or     (<a href="{% url 'iSupermarket:client_delete' client.id %}">delete</a>)  {% endif %}</h1>          <h2>Detalls:</h2>          <p>            NOM: {{ client.name }}<br/>            Cognoms: {{ client.lastName	}}<br/>            Numero Telefon:{{ client.phone }}<br/>            {% if client.was_registred_recently %}            Registrat en les ultimes 24h.<br/>            {% else %}            {{	client.registration_date }}<br/>            {% endif %}            Country:{{client.country}}<br/>            City: {{client.city}}<br/>            <br/>          </p>  <a href="{% url 'iSupermarket:client_list' %}">Tornar a la llista</a>{% endblock %}

supermarket/iSupermarket/templates/detail_companyia.html
{% extends "base.html" %}
{% block title %} iSupermarket - {{companyia}}{% endblock %}
{% block	content	%}

<span vocab="http://schema.org/" typeof="organization">
<h1>
  <span property = "name">{{ companyia.name }}</span>
  {% if user.is_staff %}
    (<a href="{% url 'iSupermarket:companyia_update' companyia.id %}">edit</a>) or
    (<a href="{% url 'iSupermarket:companyia_delete' companyia.id %}">delete</a>)
  {% elif user == client.user %}
    (<a href="{% url 'iSupermarket:companyia_update' companyia.id %}">edit</a>) or 
    (<a href="{% url 'iSupermarket:companyia_delete' companyia.id %}">delete</a>)
  {% endif %}
</h1>
          <h2>Detalls:</h2>
          <p>
             Nom: {{ companyia.name }} <br/>
             ID: {{ companyia.idNumber }}<br/>
          </p>
          <a href="{% url 'iSupermarket:companyia_list' %}">Tornar a la llista</a>
{% endblock %}

supermarket/iSupermarket/templates/detail_producte.html
{% extends "base.html" %}
{% block title %} iSupermarket - {{producte}}{% endblock %}
{% block	content	%}
<span vocab="http://schema.org/" typeof="product">
<h1>
  <span property = "name">{{ sucursal.name }}</span>
  {% if user.is_staff %}
    (<a href="{% url 'iSupermarket:producte_update' producte.id %}">edit</a>) or
    (<a href="{% url 'iSupermarket:producte_delete' producte.id %}">delete</a>)
  {% elif user == client.user %}
    (<a href="{% url 'iSupermarket:producte_update' producte.id %}">edit</a>) or 
    (<a href="{% url 'iSupermarket:producte_delete' producte.id %}">delete</a>)
  {% endif %}
</h1>
           <h2>Detalls:</h2>
          <p>
            NOM: {{ producte.name }}<br/>
            Marca: <a href="{% url 'iSupermarket:marca_detail' producte.marca.id %}">{{ producte.marca }}</a>
          </p>
          <a href="{% url 'iSupermarket:producte_list' %}">Tornar a la llista</a>
          {% endblock %}

supermarket/iSupermarket/templates/form_sucursal.html
{% extends "base.html" %}
{% block	content	%}
<h1>
	Creant la nova Sucursal
</h1>
	<form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Enviar"/>
    </form>
    </br>
    <a href="{% url 'iSupermarket:sucursal_list' %}">Tornar a la llista</a>
{% endblock %}

supermarket/iSupermarket/templates/form_user.html
{% extends "base.html" %}
{% block	content	%}
<h1>
	Registre nou usuari
</h1>
	<form method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Enviar"/>
    </form>
    </br>
    <a href="/app">Tornar a la llista</a>
{% endblock %}

supermarket/iSupermarket/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>
	Clients:
</h1>
<ul>
	<!-- Estic fent de prova aixo ho tindrem que mirar com agafar les taules automaticament-->
	<li><a href="/app/Client">Client</a></li>
	<li><a href="/app/Companyia">Companyia</a></li>
	<li><a href="/app/Marca">Marca</a></li>
	<li><a href="/app/Producte">Producte</a></li>
	<li><a href="/app/Sucursal">Sucursal</a></li>
</ul>
{% endblock %}

supermarket/iSupermarket/templates/marca.html
{% extends "base.html" %}

{% block content %}
<h1>
	Marca:

    {% if user.username %}
	<h4><a href="{% url 'iSupermarket:marca_create' %}">Afegir nou Marca</a></h4>
	{% endif %}
</h1>
<ul>
	{% for marca in Marca_list  %}
		<li><a href="{% url	'iSupermarket:marca_detail' marca.id %}">{{marca.name}}</a></li>
		{% empty %}<li> Disculpeu, encara no hi ha cap marca</li>
	{% endfor %}
</ul>
{% endblock %}

supermarket/iSupermarket/templates/sucursal_detail.html
{% extends "base.html" %}
{% block	content	%}
<h1>
  {{ sucursal }}
  <!--{%	if	user	==	restaurant.user	%}
    (<a href="{%	url	'myrestaurants:restaurant_edit'	restaurant.id	%}">edit</a>)
      {%	endif	%}-->
</h1>
          <h2>Detalls:</h2>
          <p><ul>
            <li>NOM: {{ sucursal.name }}</li>
            <li>Localitzacio: {{ sucursal.location}}</li>
            <li>{{ sucursal.zipCode}}</li>
            <li>{{ sucursal.StateOrProvince }}</li>
            <li>{{ sucursal.country }}</li>
            <li><a href="{% url 'iSupermarket:companyia_detail' sucursal.companyia.id %}">{{ sucursal.companyia }}</a></li>
          </ul></p>
          {% endblock %}

supermarket/iSupermarket/templates/update_marca.html
{% extends "base.html" %}
{% block content %}
<h1>Modificar Marca {{marca}}</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Modificar" />
</form>
{% endblock %}

supermarket/iSupermarket/templates/update_producte.html
{% extends "base.html" %}
{% block content %}
<h1>Modificar producte {{producte}}</h1>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Modificar" />
</form>
{% endblock %}